function renderClaimFlow(){
  const d=document.getElementById('claimFlow');if(!d?.open)return;const step=claimDraft.step||1;const p=claimDraft.restaurantId?DATA.find(x=>x.id===claimDraft.restaurantId):null;const content=step===1?claimStepOne(p):!p?claimStepOne(null):step===2?claimStepTwo(p):step===3?claimStepThree(p):step===4?claimStepFour(p):step===5?claimStepFive(p):claimStepSix(p);const canBack=step>1;d.innerHTML=`<div class="claim-flow"><div class="claim-head"><button class="round" data-claim-close>${icons.back}</button><span class="claim-step">Schritt ${step} von 6</span></div><div class="progress"><span style="width:${step/6*100}%"></span></div>${content}<div class="claim-actions">${canBack?'<button class="back" data-claim-back>Zurück</button>':'<button class="back" data-claim-close>Abbrechen</button>'}<button class="next ${step===6?'orange':''}" data-claim-next>${step===6?'Profil übernehmen':'Weiter'}</button></div></div>`;
  d.querySelectorAll('[data-claim-close]').forEach(x=>x.onclick=()=>{captureClaimStep(step,p||{});d.close();render()});
  d.querySelector('[data-claim-back]')?.addEventListener('click',()=>{captureClaimStep(step,p);setClaimStep(step-1)});
  d.querySelector('[data-claim-restaurant]')?.addEventListener('change',e=>{const id=+e.target.value;if(!id){claimDraft.restaurantId=null;saveClaim();renderClaimFlow();return}const np=DATA.find(x=>x.id===id);claimDraft.restaurantId=id;if(!readAudit().some(x=>x.action==='claim_started'&&Number(x.restaurantId)===id))addAudit('claim_started',id);claimDraft.profile={name:np.name,address:np.address,phone:np.phone,website:cleanSite(np)||'',hours:np.hours,description:np.description};claimDraft.services={reservation:serviceState(np.reservation),pickup:serviceState(np.pickup),delivery:serviceState(np.delivery)};saveClaim();renderClaimFlow()});
  const fileInput=d.querySelector('[data-owner-files]');if(fileInput)fileInput.onchange=async e=>{const files=[...e.target.files].slice(0,6);claimSession.thumbs=[];for(const f of files){try{const data=await resizeOwnerImage(f);claimSession.thumbs.push({name:f.name,data})}catch{}}claimDraft.imageNames=files.map(f=>f.name);if(claimSession.thumbs[0]){claimDraft.ownerHero=claimSession.thumbs[0].data;if(p)addAudit('owner_media_selected',p.id,files[0]?.name||'Bild')}saveClaim();renderClaimFlow()};
  d.querySelector('[data-rights]')?.addEventListener('change',e=>{claimDraft.rightsConfirmed=e.target.checked;saveClaim()});
  d.querySelectorAll('[data-auth-open]').forEach(x=>x.onclick=()=>openAuthFlow('login'));d.querySelectorAll('[data-auth-out]').forEach(x=>x.onclick=authLogout);
  const updateOffer=()=>{captureClaimStep(5,p);const live=d.querySelector('[data-live-offer]');if(live)live.innerHTML=offerCardHTML(claimDraft.offer)};d.querySelectorAll('[data-o-type],[data-o-title],[data-o-description],[data-o-price],[data-o-start],[data-o-end],[data-o-time]').forEach(x=>x.addEventListener('input',updateOffer));
  d.querySelectorAll('[data-plan-switch]').forEach(x=>x.onclick=()=>{claimDraft.plan=x.dataset.planSwitch;saveClaim();renderClaimFlow()});
  d.querySelector('[data-claim-next]').onclick=async()=>{
    captureClaimStep(step,p||{});
    if(step===1){if(!claimDraft.restaurantId){toast('Bitte zuerst ein Restaurant wählen');return}if(!claimDraft.contact.name||!claimDraft.contact.email||!claimDraft.verified){toast('Kontakt und Berechtigung bestätigen');return}}
    if(step===3 && claimDraft.ownerHero && !claimDraft.rightsConfirmed){toast('Bitte Bildrechte bestätigen');return}
    if(step<6){setClaimStep(step+1);return}
    if(!cloud.user){saveClaim();toast('Zum echten Absenden bitte anmelden');openAuthFlow('login');return}
    const btn=d.querySelector('[data-claim-next]');btn.disabled=true;btn.innerHTML='<span class="spinner"></span>Cloud-Claim wird gesendet';
    try{
      const result=await submitClaimCloud();
      claimDraft.claimed=false;claimDraft.verified=false;claimDraft.activePlan='free';claimDraft.requestedPlan=claimDraft.plan||'free';claimDraft.step=6;claimDraft.verification={...(claimDraft.verification||{}),status:result?.status||'pending',submittedAt:result?.claim?.submitted_at||new Date().toISOString(),verifiedAt:null,claimId:result?.claim?.id||null};if(claimDraft.offer?.title){claimDraft.offer.status='draft';addAudit('offer_drafted',claimDraft.restaurantId,claimDraft.offer.title)}addAudit('claim_submitted',claimDraft.restaurantId,result?.reused?'Bestehender Cloud-Claim geladen':'In Supabase gespeichert');saveClaim();d.close();state.view='partner';render();toast(result?.reused?'Offener Claim bereits vorhanden':'Claim erfolgreich in Supabase gespeichert')
    }catch(err){btn.disabled=false;btn.textContent='Profil übernehmen';toast(err?.message||'Cloud-Claim konnte nicht gesendet werden')}
  }
}
