import { createClient } from 'npm:@supabase/supabase-js@2'

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})
const STOP=new Set(['restaurante','restaurant','chiringuito','bar','beach','club','lounge','cafe','café','la','el','los','las','de','del','y','the','mar','menor','manga'])
function clean(v:unknown){return String(v??'').replace(/\s+/g,' ').trim()}
function fold(v:unknown){return clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function digits(v:unknown){return String(v??'').replace(/\D/g,'')}
function tokens(v:unknown){return fold(v).split(' ').filter(x=>x.length>=3&&!STOP.has(x)).slice(0,8)}
function private4(h:string){const m=h.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/);if(!m)return false;const p=m.slice(1).map(Number);if(p.some(x=>x<0||x>255))return true;const[a,b]=p;return a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)}
function private6(h:string){h=h.toLowerCase().replace(/^\[|\]$/g,'');return h==='::'||h==='::1'||h.startsWith('fc')||h.startsWith('fd')||/^fe[89ab]/.test(h)}
async function publicHttps(raw:string){let u:URL;try{u=new URL(raw)}catch{throw new Error('invalid_url')}if(u.protocol!=='https:')throw new Error('https_required');const h=u.hostname.toLowerCase();if(!h||h==='localhost'||h.endsWith('.local')||h.endsWith('.internal')||private4(h)||private6(h))throw new Error('private_target');try{const rs=await Promise.allSettled([Deno.resolveDns(h,'A'),Deno.resolveDns(h,'AAAA')]);const ips=rs.flatMap(x=>x.status==='fulfilled'?x.value:[]);if(ips.some(ip=>private4(ip)||private6(ip)))throw new Error('private_dns_target')}catch(e){if(String(e).includes('private_dns_target'))throw e}return u}
async function fetchHtml(raw:string){let u=await publicHttps(raw);for(let i=0;i<4;i++){const r=await fetch(u,{redirect:'manual',headers:{'User-Agent':'HOY-La-Manga-Social-Handoff/1.0','Accept':'text/html,*/*;q=0.2'},signal:AbortSignal.timeout(15000)});if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get('location');await r.body?.cancel().catch(()=>{});if(!loc)throw new Error('redirect_without_location');u=await publicHttps(new URL(loc,u).href);continue}if(!r.ok)throw new Error(`http_${r.status}`);return{url:u.href,html:(await r.text()).slice(0,600000)}}throw new Error('too_many_redirects')}
function visible(html:string){return fold(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' '))}
function identity(r:any,html:string,url:string){const text=visible(html).slice(0,120000),host=fold(new URL(url).hostname),ts=tokens(r.name),tail=digits(r.phone).slice(-7);let score=0;if(tail&&tail.length===7&&digits(text).includes(tail))score+=70;for(const t of ts){if(text.includes(t))score+=Math.min(18,Math.max(8,t.length*2));if(host.includes(t))score+=30}if(!ts.length)score+=25;return Math.min(100,score)}
function instagram(html:string,base:string){const found:string[]=[];for(const m of html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>/gi)){let u;try{u=new URL(m[1],base)}catch{continue}const h=u.hostname.toLowerCase();if(!/(^|\.)instagram\.com$/.test(h))continue;const p=u.pathname.replace(/^\/+|\/+$/g,'');if(!p||/^(p|reel|stories|explore|accounts|share)(\/|$)/i.test(p))continue;u.search='';u.hash='';const normalized=`https://www.instagram.com/${p.split('/')[0]}/`;if(!found.includes(normalized))found.push(normalized)}return found}
async function authAdmin(req:Request){const auth=req.headers.get('Authorization')||'',userClient=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}}}),admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);const{data:{user},error}=await userClient.auth.getUser();if(error||!user?.email||!user.email_confirmed_at)throw Object.assign(new Error('unauthorized'),{status:401});const{data:row,error:e}=await admin.from('hoy_admin_accounts').select('email,user_id,active').eq('email',user.email.toLowerCase()).eq('active',true).maybeSingle();if(e)throw e;if(!row)throw Object.assign(new Error('forbidden'),{status:403});if(row.user_id&&row.user_id!==user.id)throw Object.assign(new Error('admin_identity_mismatch'),{status:403});if(!row.user_id)await admin.from('hoy_admin_accounts').update({user_id:user.id,updated_at:new Date().toISOString()}).eq('email',user.email.toLowerCase()).is('user_id',null);return{admin}}
async function one(admin:any,id:number){const{data:r,error}=await admin.from('restaurants').select('id,name,website,phone').eq('id',id).maybeSingle();if(error)throw error;if(!r||!/^https:\/\//i.test(clean(r.website))||/instagram\.com|facebook\.com|tiktok\.com/i.test(clean(r.website)))return{restaurant_id:id,status:'no_owned_website'};let page;try{page=await fetchHtml(r.website)}catch(e){return{restaurant_id:id,status:'website_unavailable',error:clean(e)}}const score=identity(r,page.html,page.url);if(score<25)return{restaurant_id:id,status:'identity_review_required',identity_score:score};const profiles=instagram(page.html,page.url);if(!profiles.length)return{restaurant_id:id,status:'no_instagram_link',identity_score:score};const{data:sales,error:sErr}=await admin.from('venue_sales_pipeline').select('restaurant_id,contact_instagram').eq('restaurant_id',id).maybeSingle();if(sErr)throw sErr;if(clean(sales?.contact_instagram))return{restaurant_id:id,status:'already_known',identity_score:score,instagram:sales.contact_instagram};const patch={restaurant_id:id,contact_instagram:profiles[0],contact_confidence:'High',contact_source_url:page.url,contact_researched_at:new Date().toISOString(),updated_at:new Date().toISOString()};const{error:uErr}=await admin.from('venue_sales_pipeline').upsert(patch,{onConflict:'restaurant_id'});if(uErr)throw uErr;return{restaurant_id:id,status:'instagram_handed_off',identity_score:score,instagram:profiles[0]}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const{admin}=await authAdmin(req),body=await req.json().catch(()=>({})),ids=(Array.isArray(body?.restaurant_ids)?body.restaurant_ids:[]).map(Number).filter((x:number)=>Number.isInteger(x)&&x>0).slice(0,40);if(!ids.length)return json({error:'restaurant_ids_required'},400);const results=[];for(const id of ids){try{results.push(await one(admin,id))}catch(e){results.push({restaurant_id:id,status:'failed',error:clean(e)})}}return json({ok:true,processed:results.length,handed_off:results.filter((x:any)=>x.status==='instagram_handed_off').length,results})}catch(e){return json({error:clean(e)},Number((e as any)?.status)||500)}})
