-- HOY Mobility v0.1 base schema.
-- Boundary rows are operational source data imported from official IGN/CNIG geometry.
-- A fresh environment remains fail-closed until those rows are loaded.

create extension if not exists postgis with schema extensions;

create table if not exists public.mobility_service_areas (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  municipality_name text not null,
  municipality_national_code text,
  active boolean not null default true,
  valid_from date,
  valid_until date,
  verified_at timestamptz not null default now(),
  source_label text,
  source_url text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mobility_providers (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  phone_e164 text not null,
  phone_display text not null,
  alternate_phone_e164 text,
  alternate_phone_display text,
  whatsapp_e164 text,
  website text,
  active boolean not null default true,
  verified_at timestamptz not null default now(),
  source_label text,
  source_url text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mobility_provider_areas (
  provider_id bigint not null references public.mobility_providers(id) on delete cascade,
  service_area_id bigint not null references public.mobility_service_areas(id) on delete cascade,
  priority integer not null default 100 check (priority > 0),
  active boolean not null default true,
  valid_from date,
  valid_until date,
  created_at timestamptz not null default now(),
  primary key (provider_id, service_area_id)
);

create index if not exists mobility_provider_areas_service_area_idx
  on public.mobility_provider_areas(service_area_id);

create table if not exists public.mobility_municipal_boundaries (
  id bigint generated by default as identity primary key,
  municipality_name text not null unique,
  national_code text,
  source_feature_id text,
  geom extensions.geometry(MultiPolygon,4326) not null,
  source_label text not null default 'Instituto Geográfico Nacional · administrativeunit API',
  source_url text not null default 'https://api-features.ign.es/collections/administrativeunit',
  source_dataset_date date not null default '2026-02-12',
  imported_at timestamptz not null default now(),
  active boolean not null default true
);

create index if not exists mobility_municipal_boundaries_geom_gix
  on public.mobility_municipal_boundaries using gist (geom);

alter table public.mobility_service_areas enable row level security;
alter table public.mobility_providers enable row level security;
alter table public.mobility_provider_areas enable row level security;
alter table public.mobility_municipal_boundaries enable row level security;

drop policy if exists mobility_service_areas_public_read on public.mobility_service_areas;
create policy mobility_service_areas_public_read on public.mobility_service_areas
for select to anon, authenticated
using (active = true and (valid_from is null or valid_from <= current_date) and (valid_until is null or valid_until >= current_date));

drop policy if exists mobility_providers_public_read on public.mobility_providers;
create policy mobility_providers_public_read on public.mobility_providers
for select to anon, authenticated using (active = true);

drop policy if exists mobility_provider_areas_public_read on public.mobility_provider_areas;
create policy mobility_provider_areas_public_read on public.mobility_provider_areas
for select to anon, authenticated
using (active = true and (valid_from is null or valid_from <= current_date) and (valid_until is null or valid_until >= current_date));

drop policy if exists mobility_municipal_boundaries_public_read on public.mobility_municipal_boundaries;
create policy mobility_municipal_boundaries_public_read on public.mobility_municipal_boundaries
for select to anon, authenticated using (active = true);

grant select on public.mobility_service_areas, public.mobility_providers, public.mobility_provider_areas, public.mobility_municipal_boundaries to anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on public.mobility_service_areas, public.mobility_providers, public.mobility_provider_areas, public.mobility_municipal_boundaries from anon, authenticated;

insert into public.mobility_service_areas (slug,name,municipality_name,active,valid_from,source_label,source_url,notes)
values
('cartagena-coast','Cartagena · La Manga / Cabo de Palos','Cartagena',true,'2026-08-11','Ayuntamiento de Cartagena · Transportes','https://www.cartagena.es/plantillas/1.asp?idPaginaOriginal=1483&pt_idpag=1482','HOY v0.1 municipality-level container; provider scope must be verified before routing.'),
('san-javier','San Javier · La Manga Nord','San Javier',true,'2026-08-11','Ayuntamiento de San Javier · taxi ordinance','https://www.sanjavier.es/es/ayuntamiento-normativas','HOY v0.1 municipality-level pickup routing container.')
on conflict (slug) do nothing;

insert into public.mobility_providers (slug,name,phone_e164,phone_display,alternate_phone_e164,alternate_phone_display,active,source_label,source_url,notes)
values
('radio-taxi-la-manga','Radio Taxi La Manga','+34968145000','968 145 000','+34968563863','968 563 863',true,'Ayuntamiento de Cartagena · Transportes','https://www.cartagena.es/plantillas/1.asp?idPaginaOriginal=1483&pt_idpag=1482','Official Cartagena directory lists Radio Taxi La Manga for La Manga del Mar Menor (Cartagena).'),
('radio-taxi-san-javier','Radio Taxi San Javier','+34968573300','968 573 300',null,null,true,'Turismo Región de Murcia','https://www.turismoregiondemurcia.es/es/taxi/radio-taxi-san-javier-833/','Official regional tourism directory listing for Radio Taxi San Javier.')
on conflict (slug) do nothing;

insert into public.mobility_provider_areas (provider_id,service_area_id,priority,active,valid_from)
select p.id,a.id,10,true,'2026-08-11'
from public.mobility_providers p
join public.mobility_service_areas a on
  (p.slug='radio-taxi-la-manga' and a.slug='cartagena-coast') or
  (p.slug='radio-taxi-san-javier' and a.slug='san-javier')
on conflict (provider_id,service_area_id) do nothing;
